name: GitHub Acctions Demo

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  MY_HOST: '127.0.0.1'
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ vars.COMPANY_NAME }}"
      - run: echo "My host is $MY_HOST"
      - run: echo "build job ${{ github.actor }}"
  
  test-job:
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - run: echo "test job ${{ github.repository }} ${{ env.MY_HOST }}"


  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - run: echo "deploy job to production server"
  